name: Testim AI Tests
on: [push, pull_request]
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm i -g @testim/testim-cli
      - name: Run Testim Tests
        run: |
          testim \
            --token ${{ secrets.TESTIM_TOKEN }} \
            --project ${{ secrets.TESTIM_PROJECT }} \
            --suite "TS_CURA_Regression" \
            --report-file results.xml
            --grid "Testim-HA-Grid" \
      - uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: results.xml
